### ISSUE TITLE
Question on evaluation/eval_template.score.v2.0522.md

### ISSUE THREAD

**Issue by kleinzcy** [allenai/WildBench#14]
Does the prompt in https://github.com/allenai/WildBench/blob/main/evaluation/eval_template.score.v2.0522.md correct?

```
First, please output your analysis for each model response, and then summarize your assessment to three aspects: "reason A=B", "reason A>B", and "reason B>A", and finally make your choice for the final assessment.
```

**Comment by yuchenlin** [comment]
hey @kleinzcy , we're using this updated version for scoring. And we will remove the previous version. https://github.com/allenai/WildBench/blob/main/evaluation/eval_template.score.v2.md
