### ISSUE TITLE
Add princeton-nlp/gemma-2-9b-it-DPO and princeton-nlp/gemma-2-9b-it-SimPO

### ISSUE THREAD

**Issue by xiamengzhou** [allenai/WildBench#17]
### Open-weight models:
- HugingFace Model ID: princeton-nlp/gemma-2-9b-it-DPO, princeton-nlp/gemma-2-9b-it-SimPO
- Pretty Name: gemma-2-9b-it-DPO, gemma-2-9b-it-SimPO
- Supported by vLLM: yes

### Misc. 
- Contact: yumeng5@virginia.edu, mengzhou@princeton.edu
- Description: https://arxiv.org/abs/2405.14734
- Notes: We attach the evaluation results of the two models. 
[gemma-2-9b-it-DPO.json](https://github.com/user-attachments/files/16268980/gemma-2-9b-it-DPO.json)
[gemma-2-9b-it-SimPO.json](https://github.com/user-attachments/files/16268982/gemma-2-9b-it-SimPO.json)

**Comment by yuchenlin** [comment]
thank you!
