### ISSUE TITLE
How to get elo scores for a custom model ?

### ISSUE THREAD

**Issue by AbhinavDutta** [allenai/WildBench#7]
Using the files in the scripts folder, I was able to generate the .json file with the response of particular model. How can I generate elo scores with them now?

**Comment by AbhinavDutta** [comment]
Hi, any updates? Did I even do a good a job at explaining what problem I am facing?

**Comment by yuchenlin** [comment]
hey our V2 is out and the scripts for computing the scores is also described in details.
